export const ARTICLE_CREATE_SUCCESS = 'ARTICLE_CREATE_SUCCESS'
export const ARTICLE_CREATE_FAIL = 'ARTICLE_CREATE_FAIL'

export const ARTICLE_GET_SUCCESS = 'ARTICLE_GET_SUCCESS'
export const ARTICLE_GET_FAIL = 'ARTICLE_GET_FAIL'

export const ARTICLE_LIST_SUCCESS = 'ARTICLE_LIST_SUCCESS'
export const ARTICLE_LIST_FAIL = 'ARTICLE_LIST_FAIL'

export const ARTICLE_UPDATE_SUCCESS = 'ARTICLE_UPDATE_SUCCESS'
export const ARTICLE_UPDATE_FAIL = 'ARTICLE_UPDATE_FAIL'

export const ARTICLE_DELETE_SUCCESS = 'ARTICLE_DELETE_SUCCESS'
export const ARTICLE_DELETE_FAIL = 'ARTICLE_DELETE_FAIL'

export const ARTICLE_CURRENT_ID = 'ARTICLE_CURRENT_ID'
